#!/usr/bin/env python
# -*- coding: utf-8 -*-
import json
import codecs
import copy

# Read English template
with codecs.open('SAM.Picker/Languages/en.json', 'r', 'utf-8-sig') as f:
    en = json.load(f)

# Define translations for key UI elements in each language
# All other keys will fallback to English
translations = {
    'ar': {
        'app_title': 'HxB SAM Enhanced V1.2 | اختر لعبة... أي لعبة...',
        'toolbar_refresh': 'تحديث الألعاب', 'toolbar_add_game': 'إضافة لعبة',
        'toolbar_filter': 'تصفية', 'toolbar_select_all': 'تحديد الكل',
        'toolbar_clear_all': 'إلغاء التحديد', 'toolbar_bulk_reset': '🔄 إعادة تعيين جماعية',
        'toolbar_bulk_reset_tooltip': 'إعادة تعيين الإنجازات لألعاب متعددة',
        'toolbar_clear_done': '🗑️ مسح المنجزة', 'toolbar_clear_done_tooltip': 'إزالة جميع الألعاب من قسم المنجزة',
        'toolbar_cheat_sheet': '📋 ورقة الغش', 'toolbar_cheat_sheet_tooltip': 'عرض الاختصارات والنصائح',
        'toolbar_donate': '☕ تبرع', 'toolbar_donate_tooltip': 'دعم على Ko-fi',
        'toolbar_socials': '🌐 وسائل التواصل', 'toolbar_socials_tooltip': 'زيارة x.hegxib.me',
        'toolbar_disclaimer': 'ℹ إخلاء المسؤولية', 'toolbar_disclaimer_tooltip': 'عرض إخلاء المسؤولية',
        'section_selected': 'المحددة', 'section_done': 'المنجزة', 'section_other_games': 'ألعاب أخرى',
        'context_toggle_selection': 'تبديل التحديد', 'context_manage': 'إدارة',
        'context_launch': 'تشغيل', 'context_launch_random': 'تشغيل عشوائي من المحددة',
        'context_launch_queue': 'قائمة التشغيل...', 'context_launch_options': 'خيارات التشغيل...',
        'context_mark_done': 'وضع علامة كمنجز', 'context_unmark_done': 'إلغاء علامة المنجز',
        'context_remove_selected': 'إزالة من المحددة', 'context_clear_all_selections': 'مسح كل التحديدات',
        'context_reset': 'إعادة تعيين',
        'msg_loading_games': 'تحميل الألعاب...', 'msg_steam_not_running': 'Steam غير مشغل',
        'status_loading': 'جاري التحميل...', 'status_ready': 'جاهز',
        'dialog_ok': 'موافق', 'dialog_cancel': 'إلغاء', 'dialog_yes': 'نعم', 'dialog_no': 'لا',
        'language_select': '🌍 اللغة',
        'game_title': 'HxB SAM Enhanced', 'game_tab_achievements': 'الإنجازات',
        'game_tab_statistics': 'الإحصائيات', 'game_button_store': 'المتجر',
        'game_button_reset': 'إعادة تعيين', 'game_enable_stats_editing': 'تفعيل تحرير الإحصائيات',
        'game_context_unlock': 'فتح', 'game_context_lock': 'قفل',
        'game_context_invert': 'عكس التحديد', 'game_context_unlock_all': 'فتح الكل',
        'game_context_lock_all': 'قفل الكل'
    },
    'fr': {
        'app_title': 'HxB SAM Amélioré V1.2 | Choisir un jeu... N\'importe lequel...',
        'toolbar_refresh': 'Actualiser', 'toolbar_add_game': 'Ajouter',
        'toolbar_filter': 'Filtrer', 'toolbar_select_all': 'Tout sélectionner',
        'toolbar_clear_all': 'Tout désélectionner', 'toolbar_bulk_reset': '🔄 Réinitialisation groupée',
        'section_selected': 'SÉLECTIONNÉS', 'section_done': 'TERMINÉS', 'section_other_games': 'AUTRES JEUX',
        'context_toggle_selection': 'Basculer sélection', 'context_manage': 'Gérer',
        'context_launch': 'Lancer', 'context_reset': 'Réinitialiser',
        'language_select': '🌍 Langue',
        'game_tab_achievements': 'Succès', 'game_tab_statistics': 'Statistiques',
        'game_button_store': 'Boutique', 'game_button_reset': 'Réinitialiser',
        'game_context_unlock': 'Déverrouiller', 'game_context_lock': 'Verrouiller'
    },
    'de': {
        'app_title': 'HxB SAM Enhanced V1.2 | Wähle ein Spiel... Irgendein Spiel...',
        'toolbar_refresh': 'Aktualisieren', 'toolbar_add_game': 'Hinzufügen',
        'toolbar_filter': 'Filter', 'toolbar_select_all': 'Alle auswählen',
        'toolbar_clear_all': 'Alle abwählen', 'toolbar_bulk_reset': '🔄 Massen-Zurücksetzung',
        'section_selected': 'AUSGEWÄHLT', 'section_done': 'ERLEDIGT', 'section_other_games': 'ANDERE SPIELE',
        'context_toggle_selection': 'Auswahl umschalten', 'context_manage': 'Verwalten',
        'context_launch': 'Starten', 'context_reset': 'Zurücksetzen',
        'language_select': '🌍 Sprache',
        'game_tab_achievements': 'Errungenschaften', 'game_tab_statistics': 'Statistiken',
        'game_button_store': 'Shop', 'game_button_reset': 'Zurücksetzen',
        'game_context_unlock': 'Freischalten', 'game_context_lock': 'Sperren'
    },
    'es': {
        'app_title': 'HxB SAM Mejorado V1.2 | Elige un juego... Cualquier juego...',
        'toolbar_refresh': 'Actualizar', 'toolbar_add_game': 'Añadir',
        'toolbar_filter': 'Filtrar', 'toolbar_select_all': 'Seleccionar todo',
        'toolbar_clear_all': 'Deseleccionar todo', 'toolbar_bulk_reset': '🔄 Reinicio masivo',
        'section_selected': 'SELECCIONADOS', 'section_done': 'HECHOS', 'section_other_games': 'OTROS JUEGOS',
        'context_toggle_selection': 'Alternar selección', 'context_manage': 'Gestionar',
        'context_launch': 'Iniciar', 'context_reset': 'Reiniciar',
        'language_select': '🌍 Idioma',
        'game_tab_achievements': 'Logros', 'game_tab_statistics': 'Estadísticas',
        'game_button_store': 'Tienda', 'game_button_reset': 'Reiniciar',
        'game_context_unlock': 'Desbloquear', 'game_context_lock': 'Bloquear'
    },
    'ja': {
        'app_title': 'HxB SAM Enhanced V1.2 | ゲームを選択... 任意のゲーム...',
        'toolbar_refresh': 'ゲームを更新', 'toolbar_add_game': 'ゲームを追加',
        'toolbar_filter': 'フィルター', 'toolbar_select_all': 'すべて選択',
        'toolbar_clear_all': 'すべて解除', 'toolbar_bulk_reset': '🔄 一括リセット',
        'toolbar_bulk_reset_tooltip': '複数のゲームの実績をリセット',
        'toolbar_clear_done': '🗑️ 完了をクリア', 'toolbar_clear_done_tooltip': '完了セクションからすべてのゲームをクリア',
        'toolbar_cheat_sheet': '📋 チートシート', 'toolbar_cheat_sheet_tooltip': 'ショートカットとヒントを表示',
        'toolbar_donate': '☕ 寄付', 'toolbar_donate_tooltip': 'Ko-fiでサポート',
        'toolbar_socials': '🌐 ソーシャル', 'toolbar_socials_tooltip': 'x.hegxib.meを訪問',
        'toolbar_disclaimer': 'ℹ 免責事項', 'toolbar_disclaimer_tooltip': '免責事項を表示',
        'section_selected': '選択済み', 'section_done': '完了', 'section_other_games': 'その他のゲーム',
        'context_toggle_selection': '選択を切り替え', 'context_manage': '管理',
        'context_launch': '起動', 'context_launch_random': '選択済みからランダム起動',
        'context_launch_queue': '起動キュー...', 'context_launch_options': '起動オプション...',
        'context_mark_done': '完了としてマーク', 'context_unmark_done': '完了マークを解除',
        'context_remove_selected': '選択済みから削除', 'context_clear_all_selections': 'すべての選択をクリア',
        'context_reset': 'リセット',
        'msg_loading_games': 'ゲームを読み込み中...', 'msg_steam_not_running': 'Steamが起動していません',
        'status_loading': '読み込み中...', 'status_ready': '準備完了',
        'dialog_ok': 'OK', 'dialog_cancel': 'キャンセル', 'dialog_yes': 'はい', 'dialog_no': 'いいえ',
        'language_select': '🌍 言語',
        'game_title': 'HxB SAM Enhanced', 'game_tab_achievements': '実績',
        'game_tab_statistics': '統計', 'game_button_store': 'ストア',
        'game_button_reset': 'リセット', 'game_button_refresh': '更新',
        'game_enable_stats_editing': '統計編集を有効化',
        'game_context_unlock': 'ロック解除', 'game_context_lock': 'ロック',
        'game_context_invert': '選択を反転', 'game_context_unlock_all': 'すべてロック解除',
        'game_context_lock_all': 'すべてロック',
        'game_toolbar_show_only': '表示のみ', 'game_toolbar_locked': 'ロック済み',
        'game_toolbar_unlocked': 'ロック解除済み', 'game_toolbar_filter': 'フィルター',
        'game_toolbar_bulk_set_times': '一括時間設定...', 
        'game_toolbar_lock_all_tooltip': 'すべての実績をロック',
        'game_toolbar_invert_all_tooltip': 'すべての実績を反転',
        'game_toolbar_unlock_all_tooltip': 'すべての実績をロック解除',
        'game_toolbar_filter_tooltip': '名前または説明に含まれる文字を3文字以上入力',
        'game_toolbar_bulk_set_times_tooltip': '複数の実績のロック解除時間を設定',
        'game_column_name': '名前', 'game_column_description': '説明',
        'game_column_unlock_time': 'ロック解除時間', 'game_column_percent_players': 'プレイヤーの割合',
        'game_column_value': '値', 'game_column_extra': '追加情報',
        'game_auto_close_timer': '自動終了タイマー',
        'error_title': 'エラー', 'error_steam_not_running': 'Steamが起動していません。先にSteamを起動してください。',
        'error_invalid_game_id': '有効なゲームIDを入力してください。',
        'error_game_not_owned': 'このゲームを所有していません。',
        'warning_title': '警告'
    },
    'ko': {
        'app_title': 'HxB SAM Enhanced V1.2 | 게임 선택... 아무 게임이나...',
        'toolbar_refresh': '게임 새로고침', 'toolbar_add_game': '게임 추가',
        'toolbar_filter': '필터', 'toolbar_select_all': '모두 선택',
        'toolbar_clear_all': '모두 해제', 'toolbar_bulk_reset': '🔄 대량 초기화',
        'toolbar_bulk_reset_tooltip': '여러 게임의 도전 과제 초기화',
        'toolbar_clear_done': '🗑️ 완료 지우기', 'toolbar_clear_done_tooltip': '완료 섹션에서 모든 게임 제거',
        'toolbar_cheat_sheet': '📋 치트 시트', 'toolbar_cheat_sheet_tooltip': '단축키 및 팁 보기',
        'toolbar_donate': '☕ 기부', 'toolbar_donate_tooltip': 'Ko-fi에서 지원',
        'toolbar_socials': '🌐 소셜', 'toolbar_socials_tooltip': 'x.hegxib.me 방문',
        'toolbar_disclaimer': 'ℹ 면책 조항', 'toolbar_disclaimer_tooltip': '면책 조항 보기',
        'section_selected': '선택됨', 'section_done': '완료', 'section_other_games': '기타 게임',
        'context_toggle_selection': '선택 전환', 'context_manage': '관리',
        'context_launch': '실행', 'context_launch_random': '선택된 게임에서 무작위 실행',
        'context_launch_queue': '실행 대기열...', 'context_launch_options': '실행 옵션...',
        'context_mark_done': '완료로 표시', 'context_unmark_done': '완료 표시 해제',
        'context_remove_selected': '선택됨에서 제거', 'context_clear_all_selections': '모든 선택 지우기',
        'context_reset': '초기화',
        'msg_loading_games': '게임 로딩 중...', 'msg_steam_not_running': 'Steam이 실행 중이 아닙니다',
        'status_loading': '로딩 중...', 'status_ready': '준비',
        'dialog_ok': '확인', 'dialog_cancel': '취소', 'dialog_yes': '예', 'dialog_no': '아니오',
        'language_select': '🌍 언어',
        'game_title': 'HxB SAM Enhanced', 'game_tab_achievements': '도전 과제',
        'game_tab_statistics': '통계', 'game_button_store': '상점',
        'game_button_reset': '초기화', 'game_button_refresh': '새로고침',
        'game_enable_stats_editing': '통계 편집 활성화',
        'game_context_unlock': '잠금 해제', 'game_context_lock': '잠금',
        'game_context_invert': '선택 반전', 'game_context_unlock_all': '모두 잠금 해제',
        'game_context_lock_all': '모두 잠금',
        'game_toolbar_show_only': '만 표시', 'game_toolbar_locked': '잠금됨',
        'game_toolbar_unlocked': '잠금 해제됨', 'game_toolbar_filter': '필터',
        'game_toolbar_bulk_set_times': '일괄 시간 설정...', 
        'game_toolbar_lock_all_tooltip': '모든 도전 과제 잠금',
        'game_toolbar_invert_all_tooltip': '모든 도전 과제 반전',
        'game_toolbar_unlock_all_tooltip': '모든 도전 과제 잠금 해제',
        'game_toolbar_filter_tooltip': '이름 또는 설명에 나타나야 하는 문자를 3자 이상 입력',
        'game_toolbar_bulk_set_times_tooltip': '여러 도전 과제의 잠금 해제 시간 설정',
        'game_column_name': '이름', 'game_column_description': '설명',
        'game_column_unlock_time': '잠금 해제 시간', 'game_column_percent_players': '플레이어 비율',
        'game_column_value': '값', 'game_column_extra': '추가 정보',
        'game_auto_close_timer': '자동 종료 타이머',
        'error_title': '오류', 'error_steam_not_running': 'Steam이 실행되고 있지 않습니다. 먼저 Steam을 시작하세요.',
        'error_invalid_game_id': '유효한 게임 ID를 입력하세요.',
        'error_game_not_owned': '이 게임을 소유하고 있지 않습니다.',
        'warning_title': '경고'
    },
    'zh-CN': {
        'app_title': 'HxB SAM Enhanced V1.2 | 选择游戏... 任意游戏...',
        'toolbar_refresh': '刷新游戏', 'toolbar_add_game': '添加游戏',
        'toolbar_filter': '筛选', 'toolbar_select_all': '全选',
        'toolbar_clear_all': '全部取消', 'toolbar_bulk_reset': '🔄 批量重置',
        'toolbar_bulk_reset_tooltip': '重置多个游戏的成就',
        'toolbar_clear_done': '🗑️ 清除已完成', 'toolbar_clear_done_tooltip': '从已完成区域删除所有游戏',
        'toolbar_cheat_sheet': '📋 速查表', 'toolbar_cheat_sheet_tooltip': '查看快捷键和提示',
        'toolbar_donate': '☕ 捐赠', 'toolbar_donate_tooltip': '在Ko-fi上支持',
        'toolbar_socials': '🌐 社交', 'toolbar_socials_tooltip': '访问x.hegxib.me',
        'toolbar_disclaimer': 'ℹ 免责声明', 'toolbar_disclaimer_tooltip': '查看免责声明',
        'section_selected': '已选择', 'section_done': '已完成', 'section_other_games': '其他游戏',
        'context_toggle_selection': '切换选择', 'context_manage': '管理',
        'context_launch': '启动', 'context_launch_random': '从已选择中随机启动',
        'context_launch_queue': '启动队列...', 'context_launch_options': '启动选项...',
        'context_mark_done': '标记为完成', 'context_unmark_done': '取消完成标记',
        'context_remove_selected': '从已选择中移除', 'context_clear_all_selections': '清除所有选择',
        'context_reset': '重置',
        'msg_loading_games': '加载游戏中...', 'msg_steam_not_running': 'Steam未运行',
        'status_loading': '加载中...', 'status_ready': '就绪',
        'dialog_ok': '确定', 'dialog_cancel': '取消', 'dialog_yes': '是', 'dialog_no': '否',
        'language_select': '🌍 语言',
        'game_title': 'HxB SAM Enhanced', 'game_tab_achievements': '成就',
        'game_tab_statistics': '统计', 'game_button_store': '商店',
        'game_button_reset': '重置', 'game_button_refresh': '刷新',
        'game_enable_stats_editing': '启用统计编辑',
        'game_context_unlock': '解锁', 'game_context_lock': '锁定',
        'game_context_invert': '反选', 'game_context_unlock_all': '全部解锁',
        'game_context_lock_all': '全部锁定',
        'game_toolbar_show_only': '仅显示', 'game_toolbar_locked': '已锁定',
        'game_toolbar_unlocked': '已解锁', 'game_toolbar_filter': '筛选',
        'game_toolbar_bulk_set_times': '批量设置时间...', 
        'game_toolbar_lock_all_tooltip': '锁定所有成就',
        'game_toolbar_invert_all_tooltip': '反选所有成就',
        'game_toolbar_unlock_all_tooltip': '解锁所有成就',
        'game_toolbar_filter_tooltip': '输入名称或描述中必须出现的至少3个字符',
        'game_toolbar_bulk_set_times_tooltip': '设置多个成就的解锁时间',
        'game_column_name': '名称', 'game_column_description': '描述',
        'game_column_unlock_time': '解锁时间', 'game_column_percent_players': '玩家百分比',
        'game_column_value': '值', 'game_column_extra': '额外信息',
        'game_auto_close_timer': '自动关闭计时器',
        'error_title': '错误', 'error_steam_not_running': 'Steam未运行。请先启动Steam。',
        'error_invalid_game_id': '请输入有效的游戏ID。',
        'error_game_not_owned': '您不拥有该游戏。',
        'warning_title': '警告'
    },
    'zh-TW': {
        'app_title': 'HxB SAM Enhanced V1.2 | 選擇遊戲... 任意遊戲...',
        'toolbar_refresh': '重新整理遊戲', 'toolbar_add_game': '新增遊戲',
        'toolbar_filter': '篩選', 'toolbar_select_all': '全選',
        'toolbar_clear_all': '全部取消', 'toolbar_bulk_reset': '🔄 批次重設',
        'toolbar_bulk_reset_tooltip': '重設多個遊戲的成就',
        'toolbar_clear_done': '🗑️ 清除已完成', 'toolbar_clear_done_tooltip': '從已完成區域移除所有遊戲',
        'toolbar_cheat_sheet': '📋 快速指南', 'toolbar_cheat_sheet_tooltip': '查看快速鍵和提示',
        'toolbar_donate': '☕ 捐贈', 'toolbar_donate_tooltip': '在Ko-fi上支持',
        'toolbar_socials': '🌐 社交', 'toolbar_socials_tooltip': '造訪x.hegxib.me',
        'toolbar_disclaimer': 'ℹ 免責聲明', 'toolbar_disclaimer_tooltip': '查看免責聲明',
        'section_selected': '已選擇', 'section_done': '已完成', 'section_other_games': '其他遊戲',
        'context_toggle_selection': '切換選擇', 'context_manage': '管理',
        'context_launch': '啟動', 'context_launch_random': '從已選擇中隨機啟動',
        'context_launch_queue': '啟動佇列...', 'context_launch_options': '啟動選項...',
        'context_mark_done': '標記為完成', 'context_unmark_done': '取消完成標記',
        'context_remove_selected': '從已選擇中移除', 'context_clear_all_selections': '清除所有選擇',
        'context_reset': '重設',
        'msg_loading_games': '載入遊戲中...', 'msg_steam_not_running': 'Steam未執行',
        'status_loading': '載入中...', 'status_ready': '就緒',
        'dialog_ok': '確定', 'dialog_cancel': '取消', 'dialog_yes': '是', 'dialog_no': '否',
        'language_select': '🌍 語言',
        'game_title': 'HxB SAM Enhanced', 'game_tab_achievements': '成就',
        'game_tab_statistics': '統計', 'game_button_store': '商店',
        'game_button_reset': '重設', 'game_button_refresh': '重新整理',
        'game_enable_stats_editing': '啟用統計編輯',
        'game_context_unlock': '解鎖', 'game_context_lock': '鎖定',
        'game_context_invert': '反選', 'game_context_unlock_all': '全部解鎖',
        'game_context_lock_all': '全部鎖定',
        'game_toolbar_show_only': '僅顯示', 'game_toolbar_locked': '已鎖定',
        'game_toolbar_unlocked': '已解鎖', 'game_toolbar_filter': '篩選',
        'game_toolbar_bulk_set_times': '批次設定時間...', 
        'game_toolbar_lock_all_tooltip': '鎖定所有成就',
        'game_toolbar_invert_all_tooltip': '反選所有成就',
        'game_toolbar_unlock_all_tooltip': '解鎖所有成就',
        'game_toolbar_filter_tooltip': '輸入名稱或描述中必須出現的至少3個字元',
        'game_toolbar_bulk_set_times_tooltip': '設定多個成就的解鎖時間',
        'game_column_name': '名稱', 'game_column_description': '描述',
        'game_column_unlock_time': '解鎖時間', 'game_column_percent_players': '玩家百分比',
        'game_column_value': '值', 'game_column_extra': '額外資訊',
        'game_auto_close_timer': '自動關閉計時器',
        'error_title': '錯誤', 'error_steam_not_running': 'Steam未執行。請先啟動Steam。',
        'error_invalid_game_id': '請輸入有效的遊戲ID。',
        'error_game_not_owned': '您未擁有該遊戲。',
        'warning_title': '警告'
    }
}

# Create language files
for lang_code, trans_dict in translations.items():
    lang_data = copy.deepcopy(en)
    lang_data.update(trans_dict)
    
    filename = f'SAM.Picker/Languages/{lang_code}.json'
    with codecs.open(filename, 'w', 'utf-8-sig') as f:
        json.dump(lang_data, f, ensure_ascii=False, indent=2)
    
    print(f'{lang_code}.json created with {len(lang_data)} keys ({len(trans_dict)} translated)')

print('\\nAll language files created successfully!')
